version: '3'
services:
  myapp1:
    build: .
    ports:
      - "3001:3000"  # Assuming your app listens on port 3000 inside the container
  myapp2:
    build: .
    ports:
      - "3002:3000"  # Assuming your app listens on port 3000 inside the container
  loadbalancer:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - myapp1
      - myapp2

